# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from simaops.review.v1 import review_pb2 as simaops_dot_review_dot_v1_dot_review__pb2


class ReviewRequestServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateReviewRequest = channel.unary_unary(
                '/simaops.review.v1.ReviewRequestService/CreateReviewRequest',
                request_serializer=simaops_dot_review_dot_v1_dot_review__pb2.CreateReviewRequestRequest.SerializeToString,
                response_deserializer=simaops_dot_review_dot_v1_dot_review__pb2.CreateReviewRequestResponse.FromString,
                _registered_method=True)
        self.ListReviewRequests = channel.unary_unary(
                '/simaops.review.v1.ReviewRequestService/ListReviewRequests',
                request_serializer=simaops_dot_review_dot_v1_dot_review__pb2.ListReviewRequestsRequest.SerializeToString,
                response_deserializer=simaops_dot_review_dot_v1_dot_review__pb2.ListReviewRequestsResponse.FromString,
                _registered_method=True)
        self.ResolveReviewRequest = channel.unary_unary(
                '/simaops.review.v1.ReviewRequestService/ResolveReviewRequest',
                request_serializer=simaops_dot_review_dot_v1_dot_review__pb2.ResolveReviewRequestRequest.SerializeToString,
                response_deserializer=simaops_dot_review_dot_v1_dot_review__pb2.ResolveReviewRequestResponse.FromString,
                _registered_method=True)


class ReviewRequestServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateReviewRequest(self, request, context):
        """Create a review request (e.g., operator requests supervisor review for warehouse assignment)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReviewRequests(self, request, context):
        """List review requests (for supervisors/managers)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveReviewRequest(self, request, context):
        """Resolve a review request (approve or reject)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewRequestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateReviewRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReviewRequest,
                    request_deserializer=simaops_dot_review_dot_v1_dot_review__pb2.CreateReviewRequestRequest.FromString,
                    response_serializer=simaops_dot_review_dot_v1_dot_review__pb2.CreateReviewRequestResponse.SerializeToString,
            ),
            'ListReviewRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReviewRequests,
                    request_deserializer=simaops_dot_review_dot_v1_dot_review__pb2.ListReviewRequestsRequest.FromString,
                    response_serializer=simaops_dot_review_dot_v1_dot_review__pb2.ListReviewRequestsResponse.SerializeToString,
            ),
            'ResolveReviewRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveReviewRequest,
                    request_deserializer=simaops_dot_review_dot_v1_dot_review__pb2.ResolveReviewRequestRequest.FromString,
                    response_serializer=simaops_dot_review_dot_v1_dot_review__pb2.ResolveReviewRequestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simaops.review.v1.ReviewRequestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simaops.review.v1.ReviewRequestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReviewRequestService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateReviewRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.review.v1.ReviewRequestService/CreateReviewRequest',
            simaops_dot_review_dot_v1_dot_review__pb2.CreateReviewRequestRequest.SerializeToString,
            simaops_dot_review_dot_v1_dot_review__pb2.CreateReviewRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReviewRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.review.v1.ReviewRequestService/ListReviewRequests',
            simaops_dot_review_dot_v1_dot_review__pb2.ListReviewRequestsRequest.SerializeToString,
            simaops_dot_review_dot_v1_dot_review__pb2.ListReviewRequestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveReviewRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.review.v1.ReviewRequestService/ResolveReviewRequest',
            simaops_dot_review_dot_v1_dot_review__pb2.ResolveReviewRequestRequest.SerializeToString,
            simaops_dot_review_dot_v1_dot_review__pb2.ResolveReviewRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
