# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from simaops.qc.v1 import qc_pb2 as simaops_dot_qc_dot_v1_dot_qc__pb2


class QCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateQCUploadUrl = channel.unary_unary(
                '/simaops.qc.v1.QCService/CreateQCUploadUrl',
                request_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCUploadUrlRequest.SerializeToString,
                response_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCUploadUrlResponse.FromString,
                _registered_method=True)
        self.CreateQCViewUrl = channel.unary_unary(
                '/simaops.qc.v1.QCService/CreateQCViewUrl',
                request_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCViewUrlRequest.SerializeToString,
                response_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCViewUrlResponse.FromString,
                _registered_method=True)
        self.CreateQCJob = channel.unary_unary(
                '/simaops.qc.v1.QCService/CreateQCJob',
                request_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCJobRequest.SerializeToString,
                response_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCJobResponse.FromString,
                _registered_method=True)
        self.GetQCJob = channel.unary_unary(
                '/simaops.qc.v1.QCService/GetQCJob',
                request_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCJobRequest.SerializeToString,
                response_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCJobResponse.FromString,
                _registered_method=True)
        self.GetQCResult = channel.unary_unary(
                '/simaops.qc.v1.QCService/GetQCResult',
                request_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCResultRequest.SerializeToString,
                response_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCResultResponse.FromString,
                _registered_method=True)
        self.ReviewQC = channel.unary_unary(
                '/simaops.qc.v1.QCService/ReviewQC',
                request_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.ReviewQCRequest.SerializeToString,
                response_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.ReviewQCResponse.FromString,
                _registered_method=True)
        self.RetryQCJob = channel.unary_unary(
                '/simaops.qc.v1.QCService/RetryQCJob',
                request_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.RetryQCJobRequest.SerializeToString,
                response_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.RetryQCJobResponse.FromString,
                _registered_method=True)


class QCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateQCUploadUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateQCViewUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateQCJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQCJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQCResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReviewQC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryQCJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateQCUploadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQCUploadUrl,
                    request_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCUploadUrlRequest.FromString,
                    response_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCUploadUrlResponse.SerializeToString,
            ),
            'CreateQCViewUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQCViewUrl,
                    request_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCViewUrlRequest.FromString,
                    response_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCViewUrlResponse.SerializeToString,
            ),
            'CreateQCJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQCJob,
                    request_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCJobRequest.FromString,
                    response_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCJobResponse.SerializeToString,
            ),
            'GetQCJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQCJob,
                    request_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCJobRequest.FromString,
                    response_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCJobResponse.SerializeToString,
            ),
            'GetQCResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQCResult,
                    request_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCResultRequest.FromString,
                    response_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCResultResponse.SerializeToString,
            ),
            'ReviewQC': grpc.unary_unary_rpc_method_handler(
                    servicer.ReviewQC,
                    request_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.ReviewQCRequest.FromString,
                    response_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.ReviewQCResponse.SerializeToString,
            ),
            'RetryQCJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryQCJob,
                    request_deserializer=simaops_dot_qc_dot_v1_dot_qc__pb2.RetryQCJobRequest.FromString,
                    response_serializer=simaops_dot_qc_dot_v1_dot_qc__pb2.RetryQCJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simaops.qc.v1.QCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simaops.qc.v1.QCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateQCUploadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.qc.v1.QCService/CreateQCUploadUrl',
            simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCUploadUrlRequest.SerializeToString,
            simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCUploadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateQCViewUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.qc.v1.QCService/CreateQCViewUrl',
            simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCViewUrlRequest.SerializeToString,
            simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCViewUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateQCJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.qc.v1.QCService/CreateQCJob',
            simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCJobRequest.SerializeToString,
            simaops_dot_qc_dot_v1_dot_qc__pb2.CreateQCJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQCJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.qc.v1.QCService/GetQCJob',
            simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCJobRequest.SerializeToString,
            simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQCResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.qc.v1.QCService/GetQCResult',
            simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCResultRequest.SerializeToString,
            simaops_dot_qc_dot_v1_dot_qc__pb2.GetQCResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReviewQC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.qc.v1.QCService/ReviewQC',
            simaops_dot_qc_dot_v1_dot_qc__pb2.ReviewQCRequest.SerializeToString,
            simaops_dot_qc_dot_v1_dot_qc__pb2.ReviewQCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryQCJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.qc.v1.QCService/RetryQCJob',
            simaops_dot_qc_dot_v1_dot_qc__pb2.RetryQCJobRequest.SerializeToString,
            simaops_dot_qc_dot_v1_dot_qc__pb2.RetryQCJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
