# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from simaops.warehouse.v1 import warehouse_pb2 as simaops_dot_warehouse_dot_v1_dot_warehouse__pb2


class WarehouseServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListLocations = channel.unary_unary(
                '/simaops.warehouse.v1.WarehouseService/ListLocations',
                request_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListLocationsRequest.SerializeToString,
                response_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListLocationsResponse.FromString,
                _registered_method=True)
        self.RecommendSlot = channel.unary_unary(
                '/simaops.warehouse.v1.WarehouseService/RecommendSlot',
                request_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.RecommendSlotRequest.SerializeToString,
                response_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.RecommendSlotResponse.FromString,
                _registered_method=True)
        self.AssignSlot = channel.unary_unary(
                '/simaops.warehouse.v1.WarehouseService/AssignSlot',
                request_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.AssignSlotRequest.SerializeToString,
                response_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.AssignSlotResponse.FromString,
                _registered_method=True)
        self.UnassignSlot = channel.unary_unary(
                '/simaops.warehouse.v1.WarehouseService/UnassignSlot',
                request_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.UnassignSlotRequest.SerializeToString,
                response_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.UnassignSlotResponse.FromString,
                _registered_method=True)
        self.ListSlotDecisions = channel.unary_unary(
                '/simaops.warehouse.v1.WarehouseService/ListSlotDecisions',
                request_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListSlotDecisionsRequest.SerializeToString,
                response_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListSlotDecisionsResponse.FromString,
                _registered_method=True)
        self.GetWarehouseAssignments = channel.unary_unary(
                '/simaops.warehouse.v1.WarehouseService/GetWarehouseAssignments',
                request_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.GetWarehouseAssignmentsRequest.SerializeToString,
                response_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.GetWarehouseAssignmentsResponse.FromString,
                _registered_method=True)


class WarehouseServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecommendSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnassignSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSlotDecisions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWarehouseAssignments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WarehouseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLocations,
                    request_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListLocationsRequest.FromString,
                    response_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListLocationsResponse.SerializeToString,
            ),
            'RecommendSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendSlot,
                    request_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.RecommendSlotRequest.FromString,
                    response_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.RecommendSlotResponse.SerializeToString,
            ),
            'AssignSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignSlot,
                    request_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.AssignSlotRequest.FromString,
                    response_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.AssignSlotResponse.SerializeToString,
            ),
            'UnassignSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.UnassignSlot,
                    request_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.UnassignSlotRequest.FromString,
                    response_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.UnassignSlotResponse.SerializeToString,
            ),
            'ListSlotDecisions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSlotDecisions,
                    request_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListSlotDecisionsRequest.FromString,
                    response_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListSlotDecisionsResponse.SerializeToString,
            ),
            'GetWarehouseAssignments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWarehouseAssignments,
                    request_deserializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.GetWarehouseAssignmentsRequest.FromString,
                    response_serializer=simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.GetWarehouseAssignmentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simaops.warehouse.v1.WarehouseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simaops.warehouse.v1.WarehouseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WarehouseService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.warehouse.v1.WarehouseService/ListLocations',
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListLocationsRequest.SerializeToString,
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecommendSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.warehouse.v1.WarehouseService/RecommendSlot',
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.RecommendSlotRequest.SerializeToString,
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.RecommendSlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.warehouse.v1.WarehouseService/AssignSlot',
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.AssignSlotRequest.SerializeToString,
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.AssignSlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnassignSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.warehouse.v1.WarehouseService/UnassignSlot',
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.UnassignSlotRequest.SerializeToString,
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.UnassignSlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSlotDecisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.warehouse.v1.WarehouseService/ListSlotDecisions',
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListSlotDecisionsRequest.SerializeToString,
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.ListSlotDecisionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWarehouseAssignments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.warehouse.v1.WarehouseService/GetWarehouseAssignments',
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.GetWarehouseAssignmentsRequest.SerializeToString,
            simaops_dot_warehouse_dot_v1_dot_warehouse__pb2.GetWarehouseAssignmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
