replicaCount: 2

image:
  repository: ghcr.io/taling-dev/simaops-web
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3000

env:
  KEYCLOAK_ISSUER: "https://auth.161.118.244.229.sslip.io/realms/simaops"
  KEYCLOAK_CLIENT_ID: "simaops-web"
  PUBLIC_APP_URL: "https://app.161.118.244.229.sslip.io"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability:4318"
  OTEL_SERVICE_NAME: "simaops-web"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilization: 70

pdb:
  enabled: true
  minAvailable: 1

serviceMonitor:
  enabled: false
  interval: 15s

networkPolicy:
  enabled: false
