# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from simaops.admin.v1 import admin_pb2 as simaops_dot_admin_dot_v1_dot_admin__pb2


class AdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/simaops.admin.v1.AdminService/ListUsers',
                request_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.AssignRole = channel.unary_unary(
                '/simaops.admin.v1.AdminService/AssignRole',
                request_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.AssignRoleRequest.SerializeToString,
                response_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.AssignRoleResponse.FromString,
                _registered_method=True)
        self.RevokeRole = channel.unary_unary(
                '/simaops.admin.v1.AdminService/RevokeRole',
                request_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.RevokeRoleRequest.SerializeToString,
                response_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.RevokeRoleResponse.FromString,
                _registered_method=True)
        self.ListRoles = channel.unary_unary(
                '/simaops.admin.v1.AdminService/ListRoles',
                request_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListRolesRequest.SerializeToString,
                response_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListRolesResponse.FromString,
                _registered_method=True)
        self.CreateRole = channel.unary_unary(
                '/simaops.admin.v1.AdminService/CreateRole',
                request_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.CreateRoleRequest.SerializeToString,
                response_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.CreateRoleResponse.FromString,
                _registered_method=True)
        self.DeleteRole = channel.unary_unary(
                '/simaops.admin.v1.AdminService/DeleteRole',
                request_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.DeleteRoleRequest.SerializeToString,
                response_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.DeleteRoleResponse.FromString,
                _registered_method=True)
        self.ListProcedures = channel.unary_unary(
                '/simaops.admin.v1.AdminService/ListProcedures',
                request_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListProceduresRequest.SerializeToString,
                response_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListProceduresResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/simaops.admin.v1.AdminService/CreateUser',
                request_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.CreateUserResponse.FromString,
                _registered_method=True)


class AdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProcedures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListUsersRequest.FromString,
                    response_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListUsersResponse.SerializeToString,
            ),
            'AssignRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRole,
                    request_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.AssignRoleRequest.FromString,
                    response_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.AssignRoleResponse.SerializeToString,
            ),
            'RevokeRole': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeRole,
                    request_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.RevokeRoleRequest.FromString,
                    response_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.RevokeRoleResponse.SerializeToString,
            ),
            'ListRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoles,
                    request_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListRolesRequest.FromString,
                    response_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListRolesResponse.SerializeToString,
            ),
            'CreateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRole,
                    request_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.CreateRoleRequest.FromString,
                    response_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.CreateRoleResponse.SerializeToString,
            ),
            'DeleteRole': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRole,
                    request_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.DeleteRoleRequest.FromString,
                    response_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.DeleteRoleResponse.SerializeToString,
            ),
            'ListProcedures': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcedures,
                    request_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListProceduresRequest.FromString,
                    response_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.ListProceduresResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=simaops_dot_admin_dot_v1_dot_admin__pb2.CreateUserRequest.FromString,
                    response_serializer=simaops_dot_admin_dot_v1_dot_admin__pb2.CreateUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simaops.admin.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simaops.admin.v1.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.admin.v1.AdminService/ListUsers',
            simaops_dot_admin_dot_v1_dot_admin__pb2.ListUsersRequest.SerializeToString,
            simaops_dot_admin_dot_v1_dot_admin__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.admin.v1.AdminService/AssignRole',
            simaops_dot_admin_dot_v1_dot_admin__pb2.AssignRoleRequest.SerializeToString,
            simaops_dot_admin_dot_v1_dot_admin__pb2.AssignRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.admin.v1.AdminService/RevokeRole',
            simaops_dot_admin_dot_v1_dot_admin__pb2.RevokeRoleRequest.SerializeToString,
            simaops_dot_admin_dot_v1_dot_admin__pb2.RevokeRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.admin.v1.AdminService/ListRoles',
            simaops_dot_admin_dot_v1_dot_admin__pb2.ListRolesRequest.SerializeToString,
            simaops_dot_admin_dot_v1_dot_admin__pb2.ListRolesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.admin.v1.AdminService/CreateRole',
            simaops_dot_admin_dot_v1_dot_admin__pb2.CreateRoleRequest.SerializeToString,
            simaops_dot_admin_dot_v1_dot_admin__pb2.CreateRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.admin.v1.AdminService/DeleteRole',
            simaops_dot_admin_dot_v1_dot_admin__pb2.DeleteRoleRequest.SerializeToString,
            simaops_dot_admin_dot_v1_dot_admin__pb2.DeleteRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProcedures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.admin.v1.AdminService/ListProcedures',
            simaops_dot_admin_dot_v1_dot_admin__pb2.ListProceduresRequest.SerializeToString,
            simaops_dot_admin_dot_v1_dot_admin__pb2.ListProceduresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.admin.v1.AdminService/CreateUser',
            simaops_dot_admin_dot_v1_dot_admin__pb2.CreateUserRequest.SerializeToString,
            simaops_dot_admin_dot_v1_dot_admin__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
