# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from simaops.audit.v1 import audit_pb2 as simaops_dot_audit_dot_v1_dot_audit__pb2


class AuditServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAuditLogs = channel.unary_unary(
                '/simaops.audit.v1.AuditService/ListAuditLogs',
                request_serializer=simaops_dot_audit_dot_v1_dot_audit__pb2.ListAuditLogsRequest.SerializeToString,
                response_deserializer=simaops_dot_audit_dot_v1_dot_audit__pb2.ListAuditLogsResponse.FromString,
                _registered_method=True)
        self.GetEntityAuditTrail = channel.unary_unary(
                '/simaops.audit.v1.AuditService/GetEntityAuditTrail',
                request_serializer=simaops_dot_audit_dot_v1_dot_audit__pb2.GetEntityAuditTrailRequest.SerializeToString,
                response_deserializer=simaops_dot_audit_dot_v1_dot_audit__pb2.GetEntityAuditTrailResponse.FromString,
                _registered_method=True)


class AuditServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListAuditLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityAuditTrail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAuditLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuditLogs,
                    request_deserializer=simaops_dot_audit_dot_v1_dot_audit__pb2.ListAuditLogsRequest.FromString,
                    response_serializer=simaops_dot_audit_dot_v1_dot_audit__pb2.ListAuditLogsResponse.SerializeToString,
            ),
            'GetEntityAuditTrail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityAuditTrail,
                    request_deserializer=simaops_dot_audit_dot_v1_dot_audit__pb2.GetEntityAuditTrailRequest.FromString,
                    response_serializer=simaops_dot_audit_dot_v1_dot_audit__pb2.GetEntityAuditTrailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simaops.audit.v1.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simaops.audit.v1.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAuditLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.audit.v1.AuditService/ListAuditLogs',
            simaops_dot_audit_dot_v1_dot_audit__pb2.ListAuditLogsRequest.SerializeToString,
            simaops_dot_audit_dot_v1_dot_audit__pb2.ListAuditLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntityAuditTrail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.audit.v1.AuditService/GetEntityAuditTrail',
            simaops_dot_audit_dot_v1_dot_audit__pb2.GetEntityAuditTrailRequest.SerializeToString,
            simaops_dot_audit_dot_v1_dot_audit__pb2.GetEntityAuditTrailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
