# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from simaops.dashboard.v1 import dashboard_pb2 as simaops_dot_dashboard_dot_v1_dot_dashboard__pb2


class DashboardServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOpsDashboard = channel.unary_unary(
                '/simaops.dashboard.v1.DashboardService/GetOpsDashboard',
                request_serializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetOpsDashboardRequest.SerializeToString,
                response_deserializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetOpsDashboardResponse.FromString,
                _registered_method=True)
        self.GetQCMetrics = channel.unary_unary(
                '/simaops.dashboard.v1.DashboardService/GetQCMetrics',
                request_serializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCMetricsRequest.SerializeToString,
                response_deserializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCMetricsResponse.FromString,
                _registered_method=True)
        self.GetWarehouseMetrics = channel.unary_unary(
                '/simaops.dashboard.v1.DashboardService/GetWarehouseMetrics',
                request_serializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetWarehouseMetricsRequest.SerializeToString,
                response_deserializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetWarehouseMetricsResponse.FromString,
                _registered_method=True)
        self.GetQCTrend = channel.unary_unary(
                '/simaops.dashboard.v1.DashboardService/GetQCTrend',
                request_serializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCTrendRequest.SerializeToString,
                response_deserializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCTrendResponse.FromString,
                _registered_method=True)
        self.GetLatestInspection = channel.unary_unary(
                '/simaops.dashboard.v1.DashboardService/GetLatestInspection',
                request_serializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetLatestInspectionRequest.SerializeToString,
                response_deserializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetLatestInspectionResponse.FromString,
                _registered_method=True)


class DashboardServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetOpsDashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQCMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWarehouseMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQCTrend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestInspection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashboardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOpsDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOpsDashboard,
                    request_deserializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetOpsDashboardRequest.FromString,
                    response_serializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetOpsDashboardResponse.SerializeToString,
            ),
            'GetQCMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQCMetrics,
                    request_deserializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCMetricsRequest.FromString,
                    response_serializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCMetricsResponse.SerializeToString,
            ),
            'GetWarehouseMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWarehouseMetrics,
                    request_deserializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetWarehouseMetricsRequest.FromString,
                    response_serializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetWarehouseMetricsResponse.SerializeToString,
            ),
            'GetQCTrend': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQCTrend,
                    request_deserializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCTrendRequest.FromString,
                    response_serializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCTrendResponse.SerializeToString,
            ),
            'GetLatestInspection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestInspection,
                    request_deserializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetLatestInspectionRequest.FromString,
                    response_serializer=simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetLatestInspectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simaops.dashboard.v1.DashboardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simaops.dashboard.v1.DashboardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DashboardService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOpsDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.dashboard.v1.DashboardService/GetOpsDashboard',
            simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetOpsDashboardRequest.SerializeToString,
            simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetOpsDashboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQCMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.dashboard.v1.DashboardService/GetQCMetrics',
            simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCMetricsRequest.SerializeToString,
            simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWarehouseMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.dashboard.v1.DashboardService/GetWarehouseMetrics',
            simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetWarehouseMetricsRequest.SerializeToString,
            simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetWarehouseMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQCTrend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.dashboard.v1.DashboardService/GetQCTrend',
            simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCTrendRequest.SerializeToString,
            simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetQCTrendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestInspection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.dashboard.v1.DashboardService/GetLatestInspection',
            simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetLatestInspectionRequest.SerializeToString,
            simaops_dot_dashboard_dot_v1_dot_dashboard__pb2.GetLatestInspectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
