// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (id, actor_user_id, actor_role, action, entity_type, entity_id, before_json, after_json, request_id, trace_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditLogParams struct {
	ID          string          `json:"id"`
	ActorUserID string          `json:"actor_user_id"`
	ActorRole   string          `json:"actor_role"`
	Action      string          `json:"action"`
	EntityType  string          `json:"entity_type"`
	EntityID    string          `json:"entity_id"`
	BeforeJson  json.RawMessage `json:"before_json"`
	AfterJson   json.RawMessage `json:"after_json"`
	RequestID   sql.NullString  `json:"request_id"`
	TraceID     sql.NullString  `json:"trace_id"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.ID,
		arg.ActorUserID,
		arg.ActorRole,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.RequestID,
		arg.TraceID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_user_id, actor_role, action, entity_type, entity_id, before_json, after_json, request_id, trace_id, created_at FROM audit_logs ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.RequestID,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, actor_user_id, actor_role, action, entity_type, entity_id, before_json, after_json, request_id, trace_id, created_at FROM audit_logs WHERE actor_user_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAuditLogsByActorParams struct {
	ActorUserID string `json:"actor_user_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByActor, arg.ActorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.RequestID,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT id, actor_user_id, actor_role, action, entity_type, entity_id, before_json, after_json, request_id, trace_id, created_at FROM audit_logs WHERE entity_type = ? AND entity_id = ? ORDER BY created_at ASC
`

type ListAuditLogsByEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.RequestID,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
