// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatch.sql

package db

import (
	"context"
	"database/sql"
)

const countActiveDispatchesForLot = `-- name: CountActiveDispatchesForLot :one
SELECT COUNT(*) FROM dispatches WHERE lot_id = ? AND status != 'CANCELLED'
`

// A lot may only have one non-cancelled dispatch at a time. Used to reject a
// duplicate CreateDispatch for a lot already being shipped.
func (q *Queries) CountActiveDispatchesForLot(ctx context.Context, lotID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveDispatchesForLot, lotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDispatches = `-- name: CountDispatches :one
SELECT COUNT(*) FROM dispatches
`

func (q *Queries) CountDispatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDispatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDispatchesByStatus = `-- name: CountDispatchesByStatus :one
SELECT COUNT(*) FROM dispatches WHERE status = ?
`

func (q *Queries) CountDispatchesByStatus(ctx context.Context, status DispatchesStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDispatchesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDispatch = `-- name: CreateDispatch :exec
INSERT INTO dispatches (id, dispatch_number, lot_id, destination, carrier, quantity, unit, scheduled_at, notes, status, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'PENDING', ?)
`

type CreateDispatchParams struct {
	ID             string         `json:"id"`
	DispatchNumber string         `json:"dispatch_number"`
	LotID          string         `json:"lot_id"`
	Destination    string         `json:"destination"`
	Carrier        string         `json:"carrier"`
	Quantity       string         `json:"quantity"`
	Unit           string         `json:"unit"`
	ScheduledAt    sql.NullTime   `json:"scheduled_at"`
	Notes          sql.NullString `json:"notes"`
	CreatedBy      string         `json:"created_by"`
}

func (q *Queries) CreateDispatch(ctx context.Context, arg CreateDispatchParams) error {
	_, err := q.db.ExecContext(ctx, createDispatch,
		arg.ID,
		arg.DispatchNumber,
		arg.LotID,
		arg.Destination,
		arg.Carrier,
		arg.Quantity,
		arg.Unit,
		arg.ScheduledAt,
		arg.Notes,
		arg.CreatedBy,
	)
	return err
}

const getDispatch = `-- name: GetDispatch :one
SELECT id, dispatch_number, lot_id, destination, carrier, quantity, unit, scheduled_at, notes, status, created_by, created_at, updated_at FROM dispatches WHERE id = ?
`

func (q *Queries) GetDispatch(ctx context.Context, id string) (Dispatch, error) {
	row := q.db.QueryRowContext(ctx, getDispatch, id)
	var i Dispatch
	err := row.Scan(
		&i.ID,
		&i.DispatchNumber,
		&i.LotID,
		&i.Destination,
		&i.Carrier,
		&i.Quantity,
		&i.Unit,
		&i.ScheduledAt,
		&i.Notes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDispatchForUpdate = `-- name: GetDispatchForUpdate :one
SELECT id, dispatch_number, lot_id, destination, carrier, quantity, unit, scheduled_at, notes, status, created_by, created_at, updated_at FROM dispatches WHERE id = ? FOR UPDATE
`

// Locks the row for the duration of the transaction (TiDB pessimistic mode).
// Used by UpdateDispatchStatus to close the same TOCTOU race the lot FSM
// guards against: without FOR UPDATE two concurrent status changes could both
// pass the FSM check against the same source state.
func (q *Queries) GetDispatchForUpdate(ctx context.Context, id string) (Dispatch, error) {
	row := q.db.QueryRowContext(ctx, getDispatchForUpdate, id)
	var i Dispatch
	err := row.Scan(
		&i.ID,
		&i.DispatchNumber,
		&i.LotID,
		&i.Destination,
		&i.Carrier,
		&i.Quantity,
		&i.Unit,
		&i.ScheduledAt,
		&i.Notes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDispatches = `-- name: ListDispatches :many
SELECT id, dispatch_number, lot_id, destination, carrier, quantity, unit, scheduled_at, notes, status, created_by, created_at, updated_at FROM dispatches ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListDispatchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDispatches(ctx context.Context, arg ListDispatchesParams) ([]Dispatch, error) {
	rows, err := q.db.QueryContext(ctx, listDispatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispatch
	for rows.Next() {
		var i Dispatch
		if err := rows.Scan(
			&i.ID,
			&i.DispatchNumber,
			&i.LotID,
			&i.Destination,
			&i.Carrier,
			&i.Quantity,
			&i.Unit,
			&i.ScheduledAt,
			&i.Notes,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchesByLot = `-- name: ListDispatchesByLot :many
SELECT id, dispatch_number, lot_id, destination, carrier, quantity, unit, scheduled_at, notes, status, created_by, created_at, updated_at FROM dispatches WHERE lot_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListDispatchesByLotParams struct {
	LotID  string `json:"lot_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDispatchesByLot(ctx context.Context, arg ListDispatchesByLotParams) ([]Dispatch, error) {
	rows, err := q.db.QueryContext(ctx, listDispatchesByLot, arg.LotID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispatch
	for rows.Next() {
		var i Dispatch
		if err := rows.Scan(
			&i.ID,
			&i.DispatchNumber,
			&i.LotID,
			&i.Destination,
			&i.Carrier,
			&i.Quantity,
			&i.Unit,
			&i.ScheduledAt,
			&i.Notes,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchesByStatus = `-- name: ListDispatchesByStatus :many
SELECT id, dispatch_number, lot_id, destination, carrier, quantity, unit, scheduled_at, notes, status, created_by, created_at, updated_at FROM dispatches WHERE status = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListDispatchesByStatusParams struct {
	Status DispatchesStatus `json:"status"`
	Limit  int32            `json:"limit"`
	Offset int32            `json:"offset"`
}

func (q *Queries) ListDispatchesByStatus(ctx context.Context, arg ListDispatchesByStatusParams) ([]Dispatch, error) {
	rows, err := q.db.QueryContext(ctx, listDispatchesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispatch
	for rows.Next() {
		var i Dispatch
		if err := rows.Scan(
			&i.ID,
			&i.DispatchNumber,
			&i.LotID,
			&i.Destination,
			&i.Carrier,
			&i.Quantity,
			&i.Unit,
			&i.ScheduledAt,
			&i.Notes,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDispatchStatus = `-- name: UpdateDispatchStatus :exec
UPDATE dispatches SET status = ? WHERE id = ?
`

type UpdateDispatchStatusParams struct {
	Status DispatchesStatus `json:"status"`
	ID     string           `json:"id"`
}

func (q *Queries) UpdateDispatchStatus(ctx context.Context, arg UpdateDispatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDispatchStatus, arg.Status, arg.ID)
	return err
}
