// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lots.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const countLots = `-- name: CountLots :one
SELECT COUNT(*) FROM lots
`

func (q *Queries) CountLots(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLotsByStatus = `-- name: CountLotsByStatus :one
SELECT COUNT(*) FROM lots WHERE status = ?
`

func (q *Queries) CountLotsByStatus(ctx context.Context, status LotsStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLotsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLotsByStatusGroup = `-- name: CountLotsByStatusGroup :many
SELECT status, COUNT(*) as count FROM lots GROUP BY status
`

type CountLotsByStatusGroupRow struct {
	Status LotsStatus `json:"status"`
	Count  int64      `json:"count"`
}

func (q *Queries) CountLotsByStatusGroup(ctx context.Context) ([]CountLotsByStatusGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, countLotsByStatusGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountLotsByStatusGroupRow
	for rows.Next() {
		var i CountLotsByStatusGroupRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createLot = `-- name: CreateLot :exec
INSERT INTO lots (id, lot_number, supplier_name, material_name, material_type, quantity, unit, arrival_date, storage_requirement, status, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'DRAFT', ?)
`

type CreateLotParams struct {
	ID                 string           `json:"id"`
	LotNumber          string           `json:"lot_number"`
	SupplierName       string           `json:"supplier_name"`
	MaterialName       string           `json:"material_name"`
	MaterialType       LotsMaterialType `json:"material_type"`
	Quantity           string           `json:"quantity"`
	Unit               string           `json:"unit"`
	ArrivalDate        time.Time        `json:"arrival_date"`
	StorageRequirement json.RawMessage  `json:"storage_requirement"`
	CreatedBy          string           `json:"created_by"`
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) error {
	_, err := q.db.ExecContext(ctx, createLot,
		arg.ID,
		arg.LotNumber,
		arg.SupplierName,
		arg.MaterialName,
		arg.MaterialType,
		arg.Quantity,
		arg.Unit,
		arg.ArrivalDate,
		arg.StorageRequirement,
		arg.CreatedBy,
	)
	return err
}

const getLot = `-- name: GetLot :one
SELECT id, lot_number, supplier_name, material_name, material_type, quantity, unit, arrival_date, storage_requirement, status, created_by, created_at, updated_at FROM lots WHERE id = ?
`

func (q *Queries) GetLot(ctx context.Context, id string) (Lot, error) {
	row := q.db.QueryRowContext(ctx, getLot, id)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.SupplierName,
		&i.MaterialName,
		&i.MaterialType,
		&i.Quantity,
		&i.Unit,
		&i.ArrivalDate,
		&i.StorageRequirement,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLotByNumber = `-- name: GetLotByNumber :one
SELECT id, lot_number, supplier_name, material_name, material_type, quantity, unit, arrival_date, storage_requirement, status, created_by, created_at, updated_at FROM lots WHERE lot_number = ?
`

func (q *Queries) GetLotByNumber(ctx context.Context, lotNumber string) (Lot, error) {
	row := q.db.QueryRowContext(ctx, getLotByNumber, lotNumber)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.SupplierName,
		&i.MaterialName,
		&i.MaterialType,
		&i.Quantity,
		&i.Unit,
		&i.ArrivalDate,
		&i.StorageRequirement,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLotForUpdate = `-- name: GetLotForUpdate :one
SELECT id, lot_number, supplier_name, material_name, material_type, quantity, unit, arrival_date, storage_requirement, status, created_by, created_at, updated_at FROM lots WHERE id = ? FOR UPDATE
`

// Locks the row for the duration of the transaction (TiDB pessimistic mode).
// Used by UpdateLotStatus to close a TOCTOU race: without FOR UPDATE, a
// concurrent caller could change `status` between our read and our write,
// letting both transitions succeed even though only one should.
func (q *Queries) GetLotForUpdate(ctx context.Context, id string) (Lot, error) {
	row := q.db.QueryRowContext(ctx, getLotForUpdate, id)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.SupplierName,
		&i.MaterialName,
		&i.MaterialType,
		&i.Quantity,
		&i.Unit,
		&i.ArrivalDate,
		&i.StorageRequirement,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLots = `-- name: ListLots :many
SELECT id, lot_number, supplier_name, material_name, material_type, quantity, unit, arrival_date, storage_requirement, status, created_by, created_at, updated_at FROM lots ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListLotsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLots(ctx context.Context, arg ListLotsParams) ([]Lot, error) {
	rows, err := q.db.QueryContext(ctx, listLots, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lot
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.LotNumber,
			&i.SupplierName,
			&i.MaterialName,
			&i.MaterialType,
			&i.Quantity,
			&i.Unit,
			&i.ArrivalDate,
			&i.StorageRequirement,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotsByMaterialType = `-- name: ListLotsByMaterialType :many
SELECT id, lot_number, supplier_name, material_name, material_type, quantity, unit, arrival_date, storage_requirement, status, created_by, created_at, updated_at FROM lots WHERE material_type = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListLotsByMaterialTypeParams struct {
	MaterialType LotsMaterialType `json:"material_type"`
	Limit        int32            `json:"limit"`
	Offset       int32            `json:"offset"`
}

func (q *Queries) ListLotsByMaterialType(ctx context.Context, arg ListLotsByMaterialTypeParams) ([]Lot, error) {
	rows, err := q.db.QueryContext(ctx, listLotsByMaterialType, arg.MaterialType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lot
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.LotNumber,
			&i.SupplierName,
			&i.MaterialName,
			&i.MaterialType,
			&i.Quantity,
			&i.Unit,
			&i.ArrivalDate,
			&i.StorageRequirement,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotsByStatus = `-- name: ListLotsByStatus :many
SELECT id, lot_number, supplier_name, material_name, material_type, quantity, unit, arrival_date, storage_requirement, status, created_by, created_at, updated_at FROM lots WHERE status = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListLotsByStatusParams struct {
	Status LotsStatus `json:"status"`
	Limit  int32      `json:"limit"`
	Offset int32      `json:"offset"`
}

func (q *Queries) ListLotsByStatus(ctx context.Context, arg ListLotsByStatusParams) ([]Lot, error) {
	rows, err := q.db.QueryContext(ctx, listLotsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lot
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.LotNumber,
			&i.SupplierName,
			&i.MaterialName,
			&i.MaterialType,
			&i.Quantity,
			&i.Unit,
			&i.ArrivalDate,
			&i.StorageRequirement,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLotStatus = `-- name: UpdateLotStatus :exec
UPDATE lots SET status = ? WHERE id = ?
`

type UpdateLotStatusParams struct {
	Status LotsStatus `json:"status"`
	ID     string     `json:"id"`
}

func (q *Queries) UpdateLotStatus(ctx context.Context, arg UpdateLotStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLotStatus, arg.Status, arg.ID)
	return err
}
