// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type LotsMaterialType string

const (
	LotsMaterialTypeRAWBOTANICAL LotsMaterialType = "RAW_BOTANICAL"
	LotsMaterialTypeEXTRACT      LotsMaterialType = "EXTRACT"
	LotsMaterialTypePOWDER       LotsMaterialType = "POWDER"
	LotsMaterialTypeOTHER        LotsMaterialType = "OTHER"
)

func (e *LotsMaterialType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LotsMaterialType(s)
	case string:
		*e = LotsMaterialType(s)
	default:
		return fmt.Errorf("unsupported scan type for LotsMaterialType: %T", src)
	}
	return nil
}

type NullLotsMaterialType struct {
	LotsMaterialType LotsMaterialType `json:"lots_material_type"`
	Valid            bool             `json:"valid"` // Valid is true if LotsMaterialType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLotsMaterialType) Scan(value interface{}) error {
	if value == nil {
		ns.LotsMaterialType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LotsMaterialType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLotsMaterialType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LotsMaterialType), nil
}

type LotsStatus string

const (
	LotsStatusDRAFT              LotsStatus = "DRAFT"
	LotsStatusPENDINGQC          LotsStatus = "PENDING_QC"
	LotsStatusAIPROCESSING       LotsStatus = "AI_PROCESSING"
	LotsStatusQCREVIEW           LotsStatus = "QC_REVIEW"
	LotsStatusQCAPPROVED         LotsStatus = "QC_APPROVED"
	LotsStatusQCREJECTED         LotsStatus = "QC_REJECTED"
	LotsStatusWAREHOUSEASSIGNED  LotsStatus = "WAREHOUSE_ASSIGNED"
	LotsStatusREADYFORPRODUCTION LotsStatus = "READY_FOR_PRODUCTION"
	LotsStatusBLOCKED            LotsStatus = "BLOCKED"
)

func (e *LotsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LotsStatus(s)
	case string:
		*e = LotsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LotsStatus: %T", src)
	}
	return nil
}

type NullLotsStatus struct {
	LotsStatus LotsStatus `json:"lots_status"`
	Valid      bool       `json:"valid"` // Valid is true if LotsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLotsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LotsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LotsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLotsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LotsStatus), nil
}

type OutboxEventsStatus string

const (
	OutboxEventsStatusPENDING   OutboxEventsStatus = "PENDING"
	OutboxEventsStatusPUBLISHED OutboxEventsStatus = "PUBLISHED"
	OutboxEventsStatusFAILED    OutboxEventsStatus = "FAILED"
)

func (e *OutboxEventsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventsStatus(s)
	case string:
		*e = OutboxEventsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventsStatus: %T", src)
	}
	return nil
}

type NullOutboxEventsStatus struct {
	OutboxEventsStatus OutboxEventsStatus `json:"outbox_events_status"`
	Valid              bool               `json:"valid"` // Valid is true if OutboxEventsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventsStatus), nil
}

type QcJobsStatus string

const (
	QcJobsStatusQUEUED           QcJobsStatus = "QUEUED"
	QcJobsStatusPROCESSING       QcJobsStatus = "PROCESSING"
	QcJobsStatusAICOMPLETED      QcJobsStatus = "AI_COMPLETED"
	QcJobsStatusNEEDSHUMANREVIEW QcJobsStatus = "NEEDS_HUMAN_REVIEW"
	QcJobsStatusAPPROVED         QcJobsStatus = "APPROVED"
	QcJobsStatusREJECTED         QcJobsStatus = "REJECTED"
	QcJobsStatusFAILED           QcJobsStatus = "FAILED"
)

func (e *QcJobsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QcJobsStatus(s)
	case string:
		*e = QcJobsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for QcJobsStatus: %T", src)
	}
	return nil
}

type NullQcJobsStatus struct {
	QcJobsStatus QcJobsStatus `json:"qc_jobs_status"`
	Valid        bool         `json:"valid"` // Valid is true if QcJobsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQcJobsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.QcJobsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QcJobsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQcJobsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QcJobsStatus), nil
}

type QcResultsRecommendation string

const (
	QcResultsRecommendationPASS   QcResultsRecommendation = "PASS"
	QcResultsRecommendationREVIEW QcResultsRecommendation = "REVIEW"
	QcResultsRecommendationFAIL   QcResultsRecommendation = "FAIL"
)

func (e *QcResultsRecommendation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QcResultsRecommendation(s)
	case string:
		*e = QcResultsRecommendation(s)
	default:
		return fmt.Errorf("unsupported scan type for QcResultsRecommendation: %T", src)
	}
	return nil
}

type NullQcResultsRecommendation struct {
	QcResultsRecommendation QcResultsRecommendation `json:"qc_results_recommendation"`
	Valid                   bool                    `json:"valid"` // Valid is true if QcResultsRecommendation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQcResultsRecommendation) Scan(value interface{}) error {
	if value == nil {
		ns.QcResultsRecommendation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QcResultsRecommendation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQcResultsRecommendation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QcResultsRecommendation), nil
}

type QcResultsSupervisorDecision string

const (
	QcResultsSupervisorDecisionAPPROVED QcResultsSupervisorDecision = "APPROVED"
	QcResultsSupervisorDecisionREJECTED QcResultsSupervisorDecision = "REJECTED"
	QcResultsSupervisorDecisionRECHECK  QcResultsSupervisorDecision = "RECHECK"
)

func (e *QcResultsSupervisorDecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QcResultsSupervisorDecision(s)
	case string:
		*e = QcResultsSupervisorDecision(s)
	default:
		return fmt.Errorf("unsupported scan type for QcResultsSupervisorDecision: %T", src)
	}
	return nil
}

type NullQcResultsSupervisorDecision struct {
	QcResultsSupervisorDecision QcResultsSupervisorDecision `json:"qc_results_supervisor_decision"`
	Valid                       bool                        `json:"valid"` // Valid is true if QcResultsSupervisorDecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQcResultsSupervisorDecision) Scan(value interface{}) error {
	if value == nil {
		ns.QcResultsSupervisorDecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QcResultsSupervisorDecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQcResultsSupervisorDecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QcResultsSupervisorDecision), nil
}

type WarehouseAssignmentsStatus string

const (
	WarehouseAssignmentsStatusACTIVE   WarehouseAssignmentsStatus = "ACTIVE"
	WarehouseAssignmentsStatusRELEASED WarehouseAssignmentsStatus = "RELEASED"
)

func (e *WarehouseAssignmentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WarehouseAssignmentsStatus(s)
	case string:
		*e = WarehouseAssignmentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WarehouseAssignmentsStatus: %T", src)
	}
	return nil
}

type NullWarehouseAssignmentsStatus struct {
	WarehouseAssignmentsStatus WarehouseAssignmentsStatus `json:"warehouse_assignments_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if WarehouseAssignmentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWarehouseAssignmentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WarehouseAssignmentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WarehouseAssignmentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWarehouseAssignmentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WarehouseAssignmentsStatus), nil
}

type WarehouseLocationsCurrentStatus string

const (
	WarehouseLocationsCurrentStatusAVAILABLE   WarehouseLocationsCurrentStatus = "AVAILABLE"
	WarehouseLocationsCurrentStatusOCCUPIED    WarehouseLocationsCurrentStatus = "OCCUPIED"
	WarehouseLocationsCurrentStatusMAINTENANCE WarehouseLocationsCurrentStatus = "MAINTENANCE"
)

func (e *WarehouseLocationsCurrentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WarehouseLocationsCurrentStatus(s)
	case string:
		*e = WarehouseLocationsCurrentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WarehouseLocationsCurrentStatus: %T", src)
	}
	return nil
}

type NullWarehouseLocationsCurrentStatus struct {
	WarehouseLocationsCurrentStatus WarehouseLocationsCurrentStatus `json:"warehouse_locations_current_status"`
	Valid                           bool                            `json:"valid"` // Valid is true if WarehouseLocationsCurrentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWarehouseLocationsCurrentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WarehouseLocationsCurrentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WarehouseLocationsCurrentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWarehouseLocationsCurrentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WarehouseLocationsCurrentStatus), nil
}

type AuditLog struct {
	ID          string          `json:"id"`
	ActorUserID string          `json:"actor_user_id"`
	ActorRole   string          `json:"actor_role"`
	Action      string          `json:"action"`
	EntityType  string          `json:"entity_type"`
	EntityID    string          `json:"entity_id"`
	BeforeJson  json.RawMessage `json:"before_json"`
	AfterJson   json.RawMessage `json:"after_json"`
	RequestID   sql.NullString  `json:"request_id"`
	TraceID     sql.NullString  `json:"trace_id"`
	CreatedAt   time.Time       `json:"created_at"`
}

type IdempotencyKey struct {
	KeyHash      string          `json:"key_hash"`
	UserID       string          `json:"user_id"`
	Operation    string          `json:"operation"`
	ResponseJson json.RawMessage `json:"response_json"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Lot struct {
	ID                 string           `json:"id"`
	LotNumber          string           `json:"lot_number"`
	SupplierName       string           `json:"supplier_name"`
	MaterialName       string           `json:"material_name"`
	MaterialType       LotsMaterialType `json:"material_type"`
	Quantity           string           `json:"quantity"`
	Unit               string           `json:"unit"`
	ArrivalDate        time.Time        `json:"arrival_date"`
	StorageRequirement json.RawMessage  `json:"storage_requirement"`
	Status             LotsStatus       `json:"status"`
	CreatedBy          string           `json:"created_by"`
	CreatedAt          time.Time        `json:"created_at"`
	UpdatedAt          time.Time        `json:"updated_at"`
}

type OutboxEvent struct {
	ID          string             `json:"id"`
	EventType   string             `json:"event_type"`
	PayloadJson json.RawMessage    `json:"payload_json"`
	Status      OutboxEventsStatus `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	CreatedAt   time.Time          `json:"created_at"`
	PublishedAt sql.NullTime       `json:"published_at"`
}

type QcJob struct {
	ID             string         `json:"id"`
	LotID          string         `json:"lot_id"`
	ImageObjectKey string         `json:"image_object_key"`
	Status         QcJobsStatus   `json:"status"`
	RequestedBy    string         `json:"requested_by"`
	FailureReason  sql.NullString `json:"failure_reason"`
	StartedAt      sql.NullTime   `json:"started_at"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type QcResult struct {
	ID                 string                          `json:"id"`
	QcJobID            string                          `json:"qc_job_id"`
	LotID              string                          `json:"lot_id"`
	Recommendation     QcResultsRecommendation         `json:"recommendation"`
	Confidence         string                          `json:"confidence"`
	FindingsJson       json.RawMessage                 `json:"findings_json"`
	ModelVersion       string                          `json:"model_version"`
	AnnotatedImageKey  sql.NullString                  `json:"annotated_image_key"`
	SupervisorDecision NullQcResultsSupervisorDecision `json:"supervisor_decision"`
	ReviewedBy         sql.NullString                  `json:"reviewed_by"`
	ReviewReason       sql.NullString                  `json:"review_reason"`
	ReviewedAt         sql.NullTime                    `json:"reviewed_at"`
	CreatedAt          time.Time                       `json:"created_at"`
}

type Role struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type UserRole struct {
	UserID string `json:"user_id"`
	RoleID string `json:"role_id"`
}

type UsersProfile struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	FullName  string    `json:"full_name"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WarehouseAssignment struct {
	ID         string                     `json:"id"`
	LotID      string                     `json:"lot_id"`
	LocationID string                     `json:"location_id"`
	AssignedBy string                     `json:"assigned_by"`
	AssignedAt time.Time                  `json:"assigned_at"`
	Status     WarehouseAssignmentsStatus `json:"status"`
}

type WarehouseLocation struct {
	ID                string                          `json:"id"`
	Code              string                          `json:"code"`
	Zone              string                          `json:"zone"`
	TemperatureMin    string                          `json:"temperature_min"`
	TemperatureMax    string                          `json:"temperature_max"`
	HazardAllowed     json.RawMessage                 `json:"hazard_allowed"`
	DrumCompatibility json.RawMessage                 `json:"drum_compatibility"`
	Capacity          int32                           `json:"capacity"`
	CurrentStatus     WarehouseLocationsCurrentStatus `json:"current_status"`
}
