// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qc.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const avgQCConfidence = `-- name: AvgQCConfidence :one
SELECT COALESCE(AVG(confidence), 0) FROM qc_results WHERE created_at >= ?
`

func (q *Queries) AvgQCConfidence(ctx context.Context, createdAt time.Time) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, avgQCConfidence, createdAt)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const countActiveQCJobsForLot = `-- name: CountActiveQCJobsForLot :one
SELECT COUNT(*) FROM qc_jobs
WHERE lot_id = ? AND status IN ('QUEUED','PROCESSING','AI_COMPLETED','NEEDS_HUMAN_REVIEW')
`

// Active = not yet in a terminal state (APPROVED/REJECTED/FAILED). Used to
// reject a duplicate CreateQCJob while a job for the lot is still in flight.
func (q *Queries) CountActiveQCJobsForLot(ctx context.Context, lotID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveQCJobsForLot, lotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveQCJobsForLotWithImage = `-- name: CountActiveQCJobsForLotWithImage :one
SELECT COUNT(*) FROM qc_jobs
WHERE lot_id = ? AND image_object_key = ?
  AND status IN ('QUEUED','PROCESSING','AI_COMPLETED','NEEDS_HUMAN_REVIEW')
`

type CountActiveQCJobsForLotWithImageParams struct {
	LotID          string `json:"lot_id"`
	ImageObjectKey string `json:"image_object_key"`
}

// Same-image double-click guard: an active job already exists for this lot
// AND the same image. Re-submitting the identical image is a no-op we reject;
// a DIFFERENT image is a deliberate re-upload that supersedes the old job.
func (q *Queries) CountActiveQCJobsForLotWithImage(ctx context.Context, arg CountActiveQCJobsForLotWithImageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveQCJobsForLotWithImage, arg.LotID, arg.ImageObjectKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQCByRecommendation = `-- name: CountQCByRecommendation :many
SELECT recommendation, COUNT(*) as count FROM qc_results WHERE created_at >= ? GROUP BY recommendation
`

type CountQCByRecommendationRow struct {
	Recommendation QcResultsRecommendation `json:"recommendation"`
	Count          int64                   `json:"count"`
}

func (q *Queries) CountQCByRecommendation(ctx context.Context, createdAt time.Time) ([]CountQCByRecommendationRow, error) {
	rows, err := q.db.QueryContext(ctx, countQCByRecommendation, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountQCByRecommendationRow
	for rows.Next() {
		var i CountQCByRecommendationRow
		if err := rows.Scan(&i.Recommendation, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createQCJob = `-- name: CreateQCJob :exec
INSERT INTO qc_jobs (id, lot_id, image_object_key, status, requested_by)
VALUES (?, ?, ?, 'QUEUED', ?)
`

type CreateQCJobParams struct {
	ID             string `json:"id"`
	LotID          string `json:"lot_id"`
	ImageObjectKey string `json:"image_object_key"`
	RequestedBy    string `json:"requested_by"`
}

func (q *Queries) CreateQCJob(ctx context.Context, arg CreateQCJobParams) error {
	_, err := q.db.ExecContext(ctx, createQCJob,
		arg.ID,
		arg.LotID,
		arg.ImageObjectKey,
		arg.RequestedBy,
	)
	return err
}

const createQCResult = `-- name: CreateQCResult :exec
INSERT INTO qc_results (id, qc_job_id, lot_id, recommendation, confidence, findings_json, model_version, annotated_image_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateQCResultParams struct {
	ID                string                  `json:"id"`
	QcJobID           string                  `json:"qc_job_id"`
	LotID             string                  `json:"lot_id"`
	Recommendation    QcResultsRecommendation `json:"recommendation"`
	Confidence        string                  `json:"confidence"`
	FindingsJson      json.RawMessage         `json:"findings_json"`
	ModelVersion      string                  `json:"model_version"`
	AnnotatedImageKey sql.NullString          `json:"annotated_image_key"`
}

func (q *Queries) CreateQCResult(ctx context.Context, arg CreateQCResultParams) error {
	_, err := q.db.ExecContext(ctx, createQCResult,
		arg.ID,
		arg.QcJobID,
		arg.LotID,
		arg.Recommendation,
		arg.Confidence,
		arg.FindingsJson,
		arg.ModelVersion,
		arg.AnnotatedImageKey,
	)
	return err
}

const getQCJob = `-- name: GetQCJob :one
SELECT id, lot_id, image_object_key, status, requested_by, failure_reason, started_at, completed_at, created_at, updated_at FROM qc_jobs WHERE id = ?
`

func (q *Queries) GetQCJob(ctx context.Context, id string) (QcJob, error) {
	row := q.db.QueryRowContext(ctx, getQCJob, id)
	var i QcJob
	err := row.Scan(
		&i.ID,
		&i.LotID,
		&i.ImageObjectKey,
		&i.Status,
		&i.RequestedBy,
		&i.FailureReason,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQCResult = `-- name: GetQCResult :one
SELECT id, qc_job_id, lot_id, recommendation, confidence, findings_json, model_version, annotated_image_key, supervisor_decision, reviewed_by, review_reason, reviewed_at, created_at FROM qc_results WHERE qc_job_id = ?
`

func (q *Queries) GetQCResult(ctx context.Context, qcJobID string) (QcResult, error) {
	row := q.db.QueryRowContext(ctx, getQCResult, qcJobID)
	var i QcResult
	err := row.Scan(
		&i.ID,
		&i.QcJobID,
		&i.LotID,
		&i.Recommendation,
		&i.Confidence,
		&i.FindingsJson,
		&i.ModelVersion,
		&i.AnnotatedImageKey,
		&i.SupervisorDecision,
		&i.ReviewedBy,
		&i.ReviewReason,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listQCJobsByLot = `-- name: ListQCJobsByLot :many
SELECT id, lot_id, image_object_key, status, requested_by, failure_reason, started_at, completed_at, created_at, updated_at FROM qc_jobs WHERE lot_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListQCJobsByLot(ctx context.Context, lotID string) ([]QcJob, error) {
	rows, err := q.db.QueryContext(ctx, listQCJobsByLot, lotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QcJob
	for rows.Next() {
		var i QcJob
		if err := rows.Scan(
			&i.ID,
			&i.LotID,
			&i.ImageObjectKey,
			&i.Status,
			&i.RequestedBy,
			&i.FailureReason,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQCJobsByStatus = `-- name: ListQCJobsByStatus :many
SELECT id, lot_id, image_object_key, status, requested_by, failure_reason, started_at, completed_at, created_at, updated_at FROM qc_jobs WHERE status = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListQCJobsByStatusParams struct {
	Status QcJobsStatus `json:"status"`
	Limit  int32        `json:"limit"`
	Offset int32        `json:"offset"`
}

func (q *Queries) ListQCJobsByStatus(ctx context.Context, arg ListQCJobsByStatusParams) ([]QcJob, error) {
	rows, err := q.db.QueryContext(ctx, listQCJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QcJob
	for rows.Next() {
		var i QcJob
		if err := rows.Scan(
			&i.ID,
			&i.LotID,
			&i.ImageObjectKey,
			&i.Status,
			&i.RequestedBy,
			&i.FailureReason,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueQCJob = `-- name: RequeueQCJob :exec
UPDATE qc_jobs SET status='QUEUED', started_at=NULL, completed_at=NULL, failure_reason=NULL
WHERE id = ?
`

// RECHECK: re-queue an existing job so the worker re-runs AI on the SAME image.
func (q *Queries) RequeueQCJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, requeueQCJob, id)
	return err
}

const supersedeActiveQCJobsForLot = `-- name: SupersedeActiveQCJobsForLot :exec
UPDATE qc_jobs SET status='FAILED', failure_reason='superseded by new image', completed_at=NOW()
WHERE lot_id = ? AND status IN ('QUEUED','PROCESSING','AI_COMPLETED','NEEDS_HUMAN_REVIEW')
`

// Terminate any in-flight jobs for a lot (used when a new image is uploaded,
// so the stale job/result is retired). FAILED is terminal and excluded from
// the dashboard recommendation breakdown, so it doesn't skew metrics.
func (q *Queries) SupersedeActiveQCJobsForLot(ctx context.Context, lotID string) error {
	_, err := q.db.ExecContext(ctx, supersedeActiveQCJobsForLot, lotID)
	return err
}

const updateQCJobCompleted = `-- name: UpdateQCJobCompleted :exec
UPDATE qc_jobs SET status = ?, completed_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateQCJobCompletedParams struct {
	Status QcJobsStatus `json:"status"`
	ID     string       `json:"id"`
}

func (q *Queries) UpdateQCJobCompleted(ctx context.Context, arg UpdateQCJobCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateQCJobCompleted, arg.Status, arg.ID)
	return err
}

const updateQCJobFailed = `-- name: UpdateQCJobFailed :exec
UPDATE qc_jobs SET status = 'FAILED', failure_reason = ?, completed_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateQCJobFailedParams struct {
	FailureReason sql.NullString `json:"failure_reason"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateQCJobFailed(ctx context.Context, arg UpdateQCJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, updateQCJobFailed, arg.FailureReason, arg.ID)
	return err
}

const updateQCJobStarted = `-- name: UpdateQCJobStarted :exec
UPDATE qc_jobs SET status = 'PROCESSING', started_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateQCJobStarted(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateQCJobStarted, id)
	return err
}

const updateQCJobStatus = `-- name: UpdateQCJobStatus :exec
UPDATE qc_jobs SET status = ? WHERE id = ?
`

type UpdateQCJobStatusParams struct {
	Status QcJobsStatus `json:"status"`
	ID     string       `json:"id"`
}

func (q *Queries) UpdateQCJobStatus(ctx context.Context, arg UpdateQCJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateQCJobStatus, arg.Status, arg.ID)
	return err
}

const updateQCResultReview = `-- name: UpdateQCResultReview :exec
UPDATE qc_results SET supervisor_decision = ?, reviewed_by = ?, review_reason = ?, reviewed_at = CURRENT_TIMESTAMP WHERE qc_job_id = ?
`

type UpdateQCResultReviewParams struct {
	SupervisorDecision NullQcResultsSupervisorDecision `json:"supervisor_decision"`
	ReviewedBy         sql.NullString                  `json:"reviewed_by"`
	ReviewReason       sql.NullString                  `json:"review_reason"`
	QcJobID            string                          `json:"qc_job_id"`
}

func (q *Queries) UpdateQCResultReview(ctx context.Context, arg UpdateQCResultReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateQCResultReview,
		arg.SupervisorDecision,
		arg.ReviewedBy,
		arg.ReviewReason,
		arg.QcJobID,
	)
	return err
}
