// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	AvgQCConfidence(ctx context.Context, createdAt time.Time) (interface{}, error)
	// Atomically transitions a batch of PENDING events to PUBLISHING. Combined
	// with `ListClaimedOutboxEvents` immediately after, this gives the leader
	// exclusive ownership of a batch — preventing any racing leader (during
	// election handoff) or this same leader (after a recovered crash) from
	// re-publishing a row that was already taken.
	ClaimOutboxBatch(ctx context.Context, limit int32) (int64, error)
	// A lot may only have one non-cancelled dispatch at a time. Used to reject a
	// duplicate CreateDispatch for a lot already being shipped.
	CountActiveDispatchesForLot(ctx context.Context, lotID string) (int64, error)
	// Active = not yet in a terminal state (APPROVED/REJECTED/FAILED). Used to
	// reject a duplicate CreateQCJob while a job for the lot is still in flight.
	CountActiveQCJobsForLot(ctx context.Context, lotID string) (int64, error)
	// Same-image double-click guard: an active job already exists for this lot
	// AND the same image. Re-submitting the identical image is a no-op we reject;
	// a DIFFERENT image is a deliberate re-upload that supersedes the old job.
	CountActiveQCJobsForLotWithImage(ctx context.Context, arg CountActiveQCJobsForLotWithImageParams) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountDispatches(ctx context.Context) (int64, error)
	CountDispatchesByStatus(ctx context.Context, status DispatchesStatus) (int64, error)
	CountLots(ctx context.Context) (int64, error)
	CountLotsByStatus(ctx context.Context, status LotsStatus) (int64, error)
	CountLotsByStatusGroup(ctx context.Context) ([]CountLotsByStatusGroupRow, error)
	CountQCByRecommendation(ctx context.Context, createdAt time.Time) ([]CountQCByRecommendationRow, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateDispatch(ctx context.Context, arg CreateDispatchParams) error
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error
	CreateLot(ctx context.Context, arg CreateLotParams) error
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	CreateQCJob(ctx context.Context, arg CreateQCJobParams) error
	CreateQCResult(ctx context.Context, arg CreateQCResultParams) error
	CreateWarehouseAssignment(ctx context.Context, arg CreateWarehouseAssignmentParams) error
	DecrementLocationCapacity(ctx context.Context, id string) error
	DecrementLocationCapacityAtomic(ctx context.Context, id string) (int64, error)
	DeleteExpiredIdempotencyKeys(ctx context.Context) error
	GetDispatch(ctx context.Context, id string) (Dispatch, error)
	// Locks the row for the duration of the transaction (TiDB pessimistic mode).
	// Used by UpdateDispatchStatus to close the same TOCTOU race the lot FSM
	// guards against: without FOR UPDATE two concurrent status changes could both
	// pass the FSM check against the same source state.
	GetDispatchForUpdate(ctx context.Context, id string) (Dispatch, error)
	GetIdempotencyKey(ctx context.Context, keyHash string) (IdempotencyKey, error)
	GetLot(ctx context.Context, id string) (Lot, error)
	GetLotByNumber(ctx context.Context, lotNumber string) (Lot, error)
	// Locks the row for the duration of the transaction (TiDB pessimistic mode).
	// Used by UpdateLotStatus to close a TOCTOU race: without FOR UPDATE, a
	// concurrent caller could change `status` between our read and our write,
	// letting both transitions succeed even though only one should.
	GetLotForUpdate(ctx context.Context, id string) (Lot, error)
	GetQCJob(ctx context.Context, id string) (QcJob, error)
	GetQCResult(ctx context.Context, qcJobID string) (QcResult, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetUserByID(ctx context.Context, id string) (UsersProfile, error)
	GetUserByUsername(ctx context.Context, username string) (UsersProfile, error)
	GetWarehouseAssignmentByLot(ctx context.Context, lotID string) (WarehouseAssignment, error)
	GetWarehouseLocation(ctx context.Context, id string) (WarehouseLocation, error)
	IncrementLocationCapacity(ctx context.Context, id string) (int64, error)
	IncrementOutboxRetry(ctx context.Context, id string) error
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListAvailableLocations(ctx context.Context) ([]WarehouseLocation, error)
	// Reads the rows just claimed by ClaimOutboxBatch. Singleton-leader semantics
	// mean we are the only writer; the SELECT cannot see anyone else's claim
	// because no one else is allowed to claim.
	ListClaimedOutboxEvents(ctx context.Context, limit int32) ([]ListClaimedOutboxEventsRow, error)
	ListDispatches(ctx context.Context, arg ListDispatchesParams) ([]Dispatch, error)
	ListDispatchesByLot(ctx context.Context, arg ListDispatchesByLotParams) ([]Dispatch, error)
	ListDispatchesByStatus(ctx context.Context, arg ListDispatchesByStatusParams) ([]Dispatch, error)
	ListLots(ctx context.Context, arg ListLotsParams) ([]Lot, error)
	ListLotsByMaterialType(ctx context.Context, arg ListLotsByMaterialTypeParams) ([]Lot, error)
	ListLotsByStatus(ctx context.Context, arg ListLotsByStatusParams) ([]Lot, error)
	ListPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	ListQCJobsByLot(ctx context.Context, lotID string) ([]QcJob, error)
	ListQCJobsByStatus(ctx context.Context, arg ListQCJobsByStatusParams) ([]QcJob, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUserRoleNames(ctx context.Context, userID string) ([]string, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListWarehouseAssignments(ctx context.Context, arg ListWarehouseAssignmentsParams) ([]WarehouseAssignment, error)
	ListWarehouseLocations(ctx context.Context) ([]WarehouseLocation, error)
	ListWarehouseLocationsByZone(ctx context.Context, zone string) ([]WarehouseLocation, error)
	// Final failure path: retry budget exhausted. Status moves PUBLISHING → FAILED
	// so the row leaves the active queue and only resurfaces if an operator
	// manually resets it (e.g., after a NATS / config fix).
	MarkOutboxFailed(ctx context.Context, id string) error
	MarkOutboxPublished(ctx context.Context, id string) error
	// Returns a single claimed event back to PENDING with retry_count incremented.
	// Used when the publish call to NATS fails but the event hasn't yet exhausted
	// its retry budget — the next poll cycle will pick it up again.
	ReleaseClaimedToPending(ctx context.Context, id string) error
	// RECHECK: re-queue an existing job so the worker re-runs AI on the SAME image.
	RequeueQCJob(ctx context.Context, id string) error
	// Called once on publisher startup. Recovers events left in PUBLISHING by a
	// prior leader that crashed mid-publish. They go back to PENDING and the
	// new leader's next poll cycle re-claims and re-publishes them. NATS
	// `Nats-Msg-Id` dedup ensures stream consumers don't see duplicates.
	ResetStuckPublishingEvents(ctx context.Context) (int64, error)
	RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) error
	// Terminate any in-flight jobs for a lot (used when a new image is uploaded,
	// so the stale job/result is retired). FAILED is terminal and excluded from
	// the dashboard recommendation breakdown, so it doesn't skew metrics.
	SupersedeActiveQCJobsForLot(ctx context.Context, lotID string) error
	UpdateDispatchStatus(ctx context.Context, arg UpdateDispatchStatusParams) error
	UpdateIdempotencyResponse(ctx context.Context, arg UpdateIdempotencyResponseParams) error
	UpdateLocationStatus(ctx context.Context, arg UpdateLocationStatusParams) error
	UpdateLotStatus(ctx context.Context, arg UpdateLotStatusParams) error
	UpdateQCJobCompleted(ctx context.Context, arg UpdateQCJobCompletedParams) error
	UpdateQCJobFailed(ctx context.Context, arg UpdateQCJobFailedParams) error
	UpdateQCJobStarted(ctx context.Context, id string) error
	UpdateQCJobStatus(ctx context.Context, arg UpdateQCJobStatusParams) error
	UpdateQCResultReview(ctx context.Context, arg UpdateQCResultReviewParams) error
	// `capacity` is REMAINING slots (AssignSlot decrements it), so it equals
	// "available". Occupancy is the count of ACTIVE assignments for the zone's
	// locations; total = remaining + occupied, which stays stable as lots are
	// assigned (available shrinks, occupied grows). Ordered alphabetically by zone.
	ZoneCapacityMetrics(ctx context.Context) ([]ZoneCapacityMetricsRow, error)
}

var _ Querier = (*Queries)(nil)
