// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	AvgQCConfidence(ctx context.Context, createdAt time.Time) (interface{}, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountLots(ctx context.Context) (int64, error)
	CountLotsByStatus(ctx context.Context, status LotsStatus) (int64, error)
	CountLotsByStatusGroup(ctx context.Context) ([]CountLotsByStatusGroupRow, error)
	CountQCByRecommendation(ctx context.Context, createdAt time.Time) ([]CountQCByRecommendationRow, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error
	CreateLot(ctx context.Context, arg CreateLotParams) error
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	CreateQCJob(ctx context.Context, arg CreateQCJobParams) error
	CreateQCResult(ctx context.Context, arg CreateQCResultParams) error
	CreateWarehouseAssignment(ctx context.Context, arg CreateWarehouseAssignmentParams) error
	DecrementLocationCapacity(ctx context.Context, id string) error
	DeleteExpiredIdempotencyKeys(ctx context.Context) error
	GetIdempotencyKey(ctx context.Context, keyHash string) (IdempotencyKey, error)
	GetLot(ctx context.Context, id string) (Lot, error)
	GetLotByNumber(ctx context.Context, lotNumber string) (Lot, error)
	GetQCJob(ctx context.Context, id string) (QcJob, error)
	GetQCResult(ctx context.Context, qcJobID string) (QcResult, error)
	GetWarehouseAssignmentByLot(ctx context.Context, lotID string) (WarehouseAssignment, error)
	GetWarehouseLocation(ctx context.Context, id string) (WarehouseLocation, error)
	IncrementOutboxRetry(ctx context.Context, id string) error
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListAvailableLocations(ctx context.Context) ([]WarehouseLocation, error)
	ListLots(ctx context.Context, arg ListLotsParams) ([]Lot, error)
	ListLotsByMaterialType(ctx context.Context, arg ListLotsByMaterialTypeParams) ([]Lot, error)
	ListLotsByStatus(ctx context.Context, arg ListLotsByStatusParams) ([]Lot, error)
	ListPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	ListQCJobsByLot(ctx context.Context, lotID string) ([]QcJob, error)
	ListQCJobsByStatus(ctx context.Context, arg ListQCJobsByStatusParams) ([]QcJob, error)
	ListWarehouseAssignments(ctx context.Context, arg ListWarehouseAssignmentsParams) ([]WarehouseAssignment, error)
	ListWarehouseLocations(ctx context.Context) ([]WarehouseLocation, error)
	ListWarehouseLocationsByZone(ctx context.Context, zone string) ([]WarehouseLocation, error)
	MarkOutboxFailed(ctx context.Context, id string) error
	MarkOutboxPublished(ctx context.Context, id string) error
	UpdateIdempotencyResponse(ctx context.Context, arg UpdateIdempotencyResponseParams) error
	UpdateLocationStatus(ctx context.Context, arg UpdateLocationStatusParams) error
	UpdateLotStatus(ctx context.Context, arg UpdateLotStatusParams) error
	UpdateQCJobCompleted(ctx context.Context, arg UpdateQCJobCompletedParams) error
	UpdateQCJobFailed(ctx context.Context, arg UpdateQCJobFailedParams) error
	UpdateQCJobStarted(ctx context.Context, id string) error
	UpdateQCJobStatus(ctx context.Context, arg UpdateQCJobStatusParams) error
	UpdateQCResultReview(ctx context.Context, arg UpdateQCResultReviewParams) error
	ZoneCapacityMetrics(ctx context.Context) ([]ZoneCapacityMetricsRow, error)
}

var _ Querier = (*Queries)(nil)
