// Code generated by sqlc. Manual additions for review_requests table.

package db

import (
	"context"
	"database/sql"
)

const createReviewRequest = `-- name: CreateReviewRequest :exec
INSERT INTO review_requests (id, lot_id, requester_id, requester_role, target_role, request_type, reason)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateReviewRequestParams struct {
	ID           string `json:"id"`
	LotID        string `json:"lot_id"`
	RequesterID  string `json:"requester_id"`
	RequesterRole string `json:"requester_role"`
	TargetRole  string `json:"target_role"`
	RequestType string `json:"request_type"`
	Reason      string `json:"reason"`
}

func (q *Queries) CreateReviewRequest(ctx context.Context, arg CreateReviewRequestParams) error {
	_, err := q.db.ExecContext(ctx, createReviewRequest,
		arg.ID,
		arg.LotID,
		arg.RequesterID,
		arg.RequesterRole,
		arg.TargetRole,
		arg.RequestType,
		arg.Reason,
	)
	return err
}

const listReviewRequests = `-- name: ListReviewRequests :many
SELECT id, lot_id, requester_id, requester_role, target_role, request_type, reason, status, reviewed_by, review_note, created_at, reviewed_at FROM review_requests ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListReviewRequestsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListReviewRequests(ctx context.Context, arg ListReviewRequestsParams) ([]ReviewRequest, error) {
	rows, err := q.db.QueryContext(ctx, listReviewRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewRequest
	for rows.Next() {
		var i ReviewRequest
		if err := rows.Scan(
			&i.ID,
			&i.LotID,
			&i.RequesterID,
			&i.RequesterRole,
			&i.TargetRole,
			&i.RequestType,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewNote,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewRequest = `-- name: GetReviewRequest :one
SELECT id, lot_id, requester_id, requester_role, target_role, request_type, reason, status, reviewed_by, review_note, created_at, reviewed_at FROM review_requests WHERE id = ?
`

func (q *Queries) GetReviewRequest(ctx context.Context, id string) (ReviewRequest, error) {
	row := q.db.QueryRowContext(ctx, getReviewRequest, id)
	var i ReviewRequest
	err := row.Scan(
		&i.ID,
		&i.LotID,
		&i.RequesterID,
		&i.RequesterRole,
		&i.TargetRole,
		&i.RequestType,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const updateReviewRequestStatus = `-- name: UpdateReviewRequestStatus :exec
UPDATE review_requests SET status = ?, reviewed_by = ?, review_note = ?, reviewed_at = NOW() WHERE id = ?
`

type UpdateReviewRequestStatusParams struct {
	Status     ReviewRequestsStatus `json:"status"`
	ReviewedBy string               `json:"reviewed_by"`
	ReviewNote sql.NullString       `json:"review_note"`
	ID         string               `json:"id"`
}

func (q *Queries) UpdateReviewRequestStatus(ctx context.Context, arg UpdateReviewRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReviewRequestStatus,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewNote,
		arg.ID,
	)
	return err
}