// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT setting_value FROM app_settings WHERE setting_key = ?
`

func (q *Queries) GetSetting(ctx context.Context, settingKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, settingKey)
	var setting_value string
	err := row.Scan(&setting_value)
	return setting_value, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO app_settings (setting_key, setting_value) VALUES (?, ?)
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)
`

type UpsertSettingParams struct {
	SettingKey   string `json:"setting_key"`
	SettingValue string `json:"setting_value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.SettingKey, arg.SettingValue)
	return err
}
