// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT IGNORE INTO role_permissions (role_id, rpc_path) VALUES (?, ?)
`

type AddRolePermissionParams struct {
	RoleID  string `json:"role_id"`
	RpcPath string `json:"rpc_path"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, addRolePermission, arg.RoleID, arg.RpcPath)
	return err
}

const assignUserRole = `-- name: AssignUserRole :exec
INSERT IGNORE INTO user_roles (user_id, role_id) VALUES (?, ?)
`

type AssignUserRoleParams struct {
	UserID string `json:"user_id"`
	RoleID string `json:"role_id"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignUserRole, arg.UserID, arg.RoleID)
	return err
}

const countRoleMembers = `-- name: CountRoleMembers :one
SELECT COUNT(*) FROM user_roles WHERE role_id = ?
`

func (q *Queries) CountRoleMembers(ctx context.Context, roleID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoleMembers, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users_profile
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (id, name, description, is_system) VALUES (?, ?, ?, FALSE)
`

type CreateRoleParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole, arg.ID, arg.Name, arg.Description)
	return err
}

const createUserProfile = `-- name: CreateUserProfile :exec
INSERT INTO users_profile (id, username, email, full_name, active) VALUES (?, ?, ?, ?, TRUE)
`

type CreateUserProfileParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	FullName string `json:"full_name"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, createUserProfile,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.FullName,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = ? AND is_system = FALSE
`

func (q *Queries) DeleteRole(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, is_system FROM roles WHERE id = ?
`

func (q *Queries) GetRoleByID(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_system FROM roles WHERE name = ?
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, full_name, active, created_at, updated_at FROM users_profile WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UsersProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i UsersProfile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, full_name, active, created_at, updated_at FROM users_profile WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (UsersProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i UsersProfile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, full_name, active, created_at, updated_at FROM users_profile WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (UsersProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i UsersProfile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRolePermissions = `-- name: ListAllRolePermissions :many
SELECT r.name AS role_name, rp.rpc_path
FROM role_permissions rp JOIN roles r ON r.id = rp.role_id
`

type ListAllRolePermissionsRow struct {
	RoleName string `json:"role_name"`
	RpcPath  string `json:"rpc_path"`
}

func (q *Queries) ListAllRolePermissions(ctx context.Context) ([]ListAllRolePermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRolePermissionsRow
	for rows.Next() {
		var i ListAllRolePermissionsRow
		if err := rows.Scan(&i.RoleName, &i.RpcPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, is_system FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleNames = `-- name: ListUserRoleNames :many
SELECT r.name FROM user_roles ur JOIN roles r ON r.id = ur.role_id WHERE ur.user_id = ? ORDER BY r.name
`

func (q *Queries) ListUserRoleNames(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoleNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.username, u.email, u.full_name, u.active, u.created_at, u.updated_at, GROUP_CONCAT(r.name SEPARATOR ',') AS role_names
FROM users_profile u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
GROUP BY u.id, u.username, u.email, u.full_name, u.active, u.created_at, u.updated_at
ORDER BY u.username
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID        string         `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	FullName  string         `json:"full_name"`
	Active    bool           `json:"active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	RoleNames sql.NullString `json:"role_names"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserRole = `-- name: RevokeUserRole :exec
DELETE FROM user_roles WHERE user_id = ? AND role_id = ?
`

type RevokeUserRoleParams struct {
	UserID string `json:"user_id"`
	RoleID string `json:"role_id"`
}

func (q *Queries) RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, revokeUserRole, arg.UserID, arg.RoleID)
	return err
}
