// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouse.sql

package db

import (
	"context"
)

const createWarehouseAssignment = `-- name: CreateWarehouseAssignment :exec
INSERT INTO warehouse_assignments (id, lot_id, location_id, assigned_by)
VALUES (?, ?, ?, ?)
`

type CreateWarehouseAssignmentParams struct {
	ID         string `json:"id"`
	LotID      string `json:"lot_id"`
	LocationID string `json:"location_id"`
	AssignedBy string `json:"assigned_by"`
}

func (q *Queries) CreateWarehouseAssignment(ctx context.Context, arg CreateWarehouseAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, createWarehouseAssignment,
		arg.ID,
		arg.LotID,
		arg.LocationID,
		arg.AssignedBy,
	)
	return err
}

const decrementLocationCapacity = `-- name: DecrementLocationCapacity :exec
UPDATE warehouse_locations SET capacity = capacity - 1 WHERE id = ? AND capacity > 0
`

func (q *Queries) DecrementLocationCapacity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, decrementLocationCapacity, id)
	return err
}

const decrementLocationCapacityAtomic = `-- name: DecrementLocationCapacityAtomic :execrows
UPDATE warehouse_locations SET capacity = capacity - 1 WHERE id = ? AND capacity > 0
`

func (q *Queries) DecrementLocationCapacityAtomic(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, decrementLocationCapacityAtomic, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWarehouseAssignmentByLot = `-- name: GetWarehouseAssignmentByLot :one
SELECT id, lot_id, location_id, assigned_by, assigned_at, status FROM warehouse_assignments WHERE lot_id = ? AND status = 'ACTIVE'
`

func (q *Queries) GetWarehouseAssignmentByLot(ctx context.Context, lotID string) (WarehouseAssignment, error) {
	row := q.db.QueryRowContext(ctx, getWarehouseAssignmentByLot, lotID)
	var i WarehouseAssignment
	err := row.Scan(
		&i.ID,
		&i.LotID,
		&i.LocationID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.Status,
	)
	return i, err
}

const getWarehouseLocation = `-- name: GetWarehouseLocation :one
SELECT id, code, zone, temperature_min, temperature_max, hazard_allowed, drum_compatibility, capacity, current_status FROM warehouse_locations WHERE id = ?
`

func (q *Queries) GetWarehouseLocation(ctx context.Context, id string) (WarehouseLocation, error) {
	row := q.db.QueryRowContext(ctx, getWarehouseLocation, id)
	var i WarehouseLocation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Zone,
		&i.TemperatureMin,
		&i.TemperatureMax,
		&i.HazardAllowed,
		&i.DrumCompatibility,
		&i.Capacity,
		&i.CurrentStatus,
	)
	return i, err
}

const incrementLocationCapacity = `-- name: IncrementLocationCapacity :execrows
UPDATE warehouse_locations SET capacity = capacity + 1 WHERE id = ?
`

func (q *Queries) IncrementLocationCapacity(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementLocationCapacity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAvailableLocations = `-- name: ListAvailableLocations :many
SELECT id, code, zone, temperature_min, temperature_max, hazard_allowed, drum_compatibility, capacity, current_status FROM warehouse_locations WHERE current_status = 'AVAILABLE' AND capacity > 0 ORDER BY zone, code
`

func (q *Queries) ListAvailableLocations(ctx context.Context) ([]WarehouseLocation, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarehouseLocation
	for rows.Next() {
		var i WarehouseLocation
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Zone,
			&i.TemperatureMin,
			&i.TemperatureMax,
			&i.HazardAllowed,
			&i.DrumCompatibility,
			&i.Capacity,
			&i.CurrentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouseAssignments = `-- name: ListWarehouseAssignments :many
SELECT id, lot_id, location_id, assigned_by, assigned_at, status FROM warehouse_assignments ORDER BY assigned_at DESC LIMIT ? OFFSET ?
`

type ListWarehouseAssignmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWarehouseAssignments(ctx context.Context, arg ListWarehouseAssignmentsParams) ([]WarehouseAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listWarehouseAssignments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarehouseAssignment
	for rows.Next() {
		var i WarehouseAssignment
		if err := rows.Scan(
			&i.ID,
			&i.LotID,
			&i.LocationID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouseLocations = `-- name: ListWarehouseLocations :many
SELECT id, code, zone, temperature_min, temperature_max, hazard_allowed, drum_compatibility, capacity, current_status FROM warehouse_locations ORDER BY zone, code
`

func (q *Queries) ListWarehouseLocations(ctx context.Context) ([]WarehouseLocation, error) {
	rows, err := q.db.QueryContext(ctx, listWarehouseLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarehouseLocation
	for rows.Next() {
		var i WarehouseLocation
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Zone,
			&i.TemperatureMin,
			&i.TemperatureMax,
			&i.HazardAllowed,
			&i.DrumCompatibility,
			&i.Capacity,
			&i.CurrentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouseLocationsByZone = `-- name: ListWarehouseLocationsByZone :many
SELECT id, code, zone, temperature_min, temperature_max, hazard_allowed, drum_compatibility, capacity, current_status FROM warehouse_locations WHERE zone = ? ORDER BY code
`

func (q *Queries) ListWarehouseLocationsByZone(ctx context.Context, zone string) ([]WarehouseLocation, error) {
	rows, err := q.db.QueryContext(ctx, listWarehouseLocationsByZone, zone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarehouseLocation
	for rows.Next() {
		var i WarehouseLocation
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Zone,
			&i.TemperatureMin,
			&i.TemperatureMax,
			&i.HazardAllowed,
			&i.DrumCompatibility,
			&i.Capacity,
			&i.CurrentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocationStatus = `-- name: UpdateLocationStatus :exec
UPDATE warehouse_locations SET current_status = ? WHERE id = ?
`

type UpdateLocationStatusParams struct {
	CurrentStatus WarehouseLocationsCurrentStatus `json:"current_status"`
	ID            string                          `json:"id"`
}

func (q *Queries) UpdateLocationStatus(ctx context.Context, arg UpdateLocationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLocationStatus, arg.CurrentStatus, arg.ID)
	return err
}

const zoneCapacityMetrics = `-- name: ZoneCapacityMetrics :many
SELECT l.zone,
       SUM(l.capacity) + COALESCE(SUM(ac.cnt), 0) AS total_capacity,
       COALESCE(SUM(ac.cnt), 0) AS occupied,
       SUM(l.capacity) AS available
FROM warehouse_locations l
LEFT JOIN (
  SELECT location_id, COUNT(*) AS cnt
  FROM warehouse_assignments WHERE status = 'ACTIVE' GROUP BY location_id
) ac ON ac.location_id = l.id
GROUP BY l.zone ORDER BY l.zone
`

type ZoneCapacityMetricsRow struct {
	Zone          string      `json:"zone"`
	TotalCapacity int32       `json:"total_capacity"`
	Occupied      interface{} `json:"occupied"`
	Available     interface{} `json:"available"`
}

// `capacity` is REMAINING slots (AssignSlot decrements it), so it equals
// "available". Occupancy is the count of ACTIVE assignments for the zone's
// locations; total = remaining + occupied, which stays stable as lots are
// assigned (available shrinks, occupied grows). Ordered alphabetically by zone.
func (q *Queries) ZoneCapacityMetrics(ctx context.Context) ([]ZoneCapacityMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, zoneCapacityMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZoneCapacityMetricsRow
	for rows.Next() {
		var i ZoneCapacityMetricsRow
		if err := rows.Scan(
			&i.Zone,
			&i.TotalCapacity,
			&i.Occupied,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
