# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from simaops.lot.v1 import lot_pb2 as simaops_dot_lot_dot_v1_dot_lot__pb2


class LotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLot = channel.unary_unary(
                '/simaops.lot.v1.LotService/CreateLot',
                request_serializer=simaops_dot_lot_dot_v1_dot_lot__pb2.CreateLotRequest.SerializeToString,
                response_deserializer=simaops_dot_lot_dot_v1_dot_lot__pb2.CreateLotResponse.FromString,
                _registered_method=True)
        self.GetLot = channel.unary_unary(
                '/simaops.lot.v1.LotService/GetLot',
                request_serializer=simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotRequest.SerializeToString,
                response_deserializer=simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotResponse.FromString,
                _registered_method=True)
        self.ListLots = channel.unary_unary(
                '/simaops.lot.v1.LotService/ListLots',
                request_serializer=simaops_dot_lot_dot_v1_dot_lot__pb2.ListLotsRequest.SerializeToString,
                response_deserializer=simaops_dot_lot_dot_v1_dot_lot__pb2.ListLotsResponse.FromString,
                _registered_method=True)
        self.UpdateLotStatus = channel.unary_unary(
                '/simaops.lot.v1.LotService/UpdateLotStatus',
                request_serializer=simaops_dot_lot_dot_v1_dot_lot__pb2.UpdateLotStatusRequest.SerializeToString,
                response_deserializer=simaops_dot_lot_dot_v1_dot_lot__pb2.UpdateLotStatusResponse.FromString,
                _registered_method=True)
        self.GetLotTimeline = channel.unary_unary(
                '/simaops.lot.v1.LotService/GetLotTimeline',
                request_serializer=simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotTimelineRequest.SerializeToString,
                response_deserializer=simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotTimelineResponse.FromString,
                _registered_method=True)


class LotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateLot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLotStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLotTimeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLot,
                    request_deserializer=simaops_dot_lot_dot_v1_dot_lot__pb2.CreateLotRequest.FromString,
                    response_serializer=simaops_dot_lot_dot_v1_dot_lot__pb2.CreateLotResponse.SerializeToString,
            ),
            'GetLot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLot,
                    request_deserializer=simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotRequest.FromString,
                    response_serializer=simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotResponse.SerializeToString,
            ),
            'ListLots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLots,
                    request_deserializer=simaops_dot_lot_dot_v1_dot_lot__pb2.ListLotsRequest.FromString,
                    response_serializer=simaops_dot_lot_dot_v1_dot_lot__pb2.ListLotsResponse.SerializeToString,
            ),
            'UpdateLotStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLotStatus,
                    request_deserializer=simaops_dot_lot_dot_v1_dot_lot__pb2.UpdateLotStatusRequest.FromString,
                    response_serializer=simaops_dot_lot_dot_v1_dot_lot__pb2.UpdateLotStatusResponse.SerializeToString,
            ),
            'GetLotTimeline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLotTimeline,
                    request_deserializer=simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotTimelineRequest.FromString,
                    response_serializer=simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotTimelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simaops.lot.v1.LotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simaops.lot.v1.LotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateLot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.lot.v1.LotService/CreateLot',
            simaops_dot_lot_dot_v1_dot_lot__pb2.CreateLotRequest.SerializeToString,
            simaops_dot_lot_dot_v1_dot_lot__pb2.CreateLotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.lot.v1.LotService/GetLot',
            simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotRequest.SerializeToString,
            simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.lot.v1.LotService/ListLots',
            simaops_dot_lot_dot_v1_dot_lot__pb2.ListLotsRequest.SerializeToString,
            simaops_dot_lot_dot_v1_dot_lot__pb2.ListLotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLotStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.lot.v1.LotService/UpdateLotStatus',
            simaops_dot_lot_dot_v1_dot_lot__pb2.UpdateLotStatusRequest.SerializeToString,
            simaops_dot_lot_dot_v1_dot_lot__pb2.UpdateLotStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLotTimeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.lot.v1.LotService/GetLotTimeline',
            simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotTimelineRequest.SerializeToString,
            simaops_dot_lot_dot_v1_dot_lot__pb2.GetLotTimelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
