# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from simaops.dispatch.v1 import dispatch_pb2 as simaops_dot_dispatch_dot_v1_dot_dispatch__pb2


class DispatchServiceStub(object):
    """DispatchService is the final stage of the Integrated Operations System:
    it tracks finished, production-ready lots leaving the facility — closing
    the loop from supplier intake → QC → warehouse → production handoff →
    dispatch in a single auditable source of truth.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDispatch = channel.unary_unary(
                '/simaops.dispatch.v1.DispatchService/CreateDispatch',
                request_serializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.CreateDispatchRequest.SerializeToString,
                response_deserializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.CreateDispatchResponse.FromString,
                _registered_method=True)
        self.GetDispatch = channel.unary_unary(
                '/simaops.dispatch.v1.DispatchService/GetDispatch',
                request_serializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.GetDispatchRequest.SerializeToString,
                response_deserializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.GetDispatchResponse.FromString,
                _registered_method=True)
        self.ListDispatches = channel.unary_unary(
                '/simaops.dispatch.v1.DispatchService/ListDispatches',
                request_serializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.ListDispatchesRequest.SerializeToString,
                response_deserializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.ListDispatchesResponse.FromString,
                _registered_method=True)
        self.UpdateDispatchStatus = channel.unary_unary(
                '/simaops.dispatch.v1.DispatchService/UpdateDispatchStatus',
                request_serializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.UpdateDispatchStatusRequest.SerializeToString,
                response_deserializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.UpdateDispatchStatusResponse.FromString,
                _registered_method=True)


class DispatchServiceServicer(object):
    """DispatchService is the final stage of the Integrated Operations System:
    it tracks finished, production-ready lots leaving the facility — closing
    the loop from supplier intake → QC → warehouse → production handoff →
    dispatch in a single auditable source of truth.
    """

    def CreateDispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDispatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDispatchStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDispatch,
                    request_deserializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.CreateDispatchRequest.FromString,
                    response_serializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.CreateDispatchResponse.SerializeToString,
            ),
            'GetDispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDispatch,
                    request_deserializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.GetDispatchRequest.FromString,
                    response_serializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.GetDispatchResponse.SerializeToString,
            ),
            'ListDispatches': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDispatches,
                    request_deserializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.ListDispatchesRequest.FromString,
                    response_serializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.ListDispatchesResponse.SerializeToString,
            ),
            'UpdateDispatchStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDispatchStatus,
                    request_deserializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.UpdateDispatchStatusRequest.FromString,
                    response_serializer=simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.UpdateDispatchStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simaops.dispatch.v1.DispatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simaops.dispatch.v1.DispatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DispatchService(object):
    """DispatchService is the final stage of the Integrated Operations System:
    it tracks finished, production-ready lots leaving the facility — closing
    the loop from supplier intake → QC → warehouse → production handoff →
    dispatch in a single auditable source of truth.
    """

    @staticmethod
    def CreateDispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.dispatch.v1.DispatchService/CreateDispatch',
            simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.CreateDispatchRequest.SerializeToString,
            simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.CreateDispatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.dispatch.v1.DispatchService/GetDispatch',
            simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.GetDispatchRequest.SerializeToString,
            simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.GetDispatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDispatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.dispatch.v1.DispatchService/ListDispatches',
            simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.ListDispatchesRequest.SerializeToString,
            simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.ListDispatchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDispatchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simaops.dispatch.v1.DispatchService/UpdateDispatchStatus',
            simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.UpdateDispatchStatusRequest.SerializeToString,
            simaops_dot_dispatch_dot_v1_dot_dispatch__pb2.UpdateDispatchStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
